version: '3'

services:
# ======================================================== #
#                ░█▀█░█▀█░▀█▀░░░█▀█░█░█░█▀█                #
#                ░█▀█░█▀▀░░█░░░░█▀▀░█▀█░█▀▀                #
#                ░▀░▀░▀░░░▀▀▀░░░▀░░░▀░▀░▀░░                #
# ======================================================== #
  api:
    image: php:8.2-apache
    hostname: api_php
    ports:
      - "${API_HOST_PORT}:80"
    volumes:
      - ../immo-api-php-main/:/var/www
      - ../immo-api-php-main/public:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile.api

  database:
    image: mysql:8.0
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_HOST_PORT}
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../immo-api-php-main/sql:/var/lib/mysql

# ======================================================== #
#                   ░█░█░█░█░█▀▀░▀▀█░█▀▀                   #
#                   ░▀▄▀░█░█░█▀▀░░░█░▀▀█                   #
#                   ░░▀░░▀▀▀░▀▀▀░▀▀░░▀▀▀                   #
# ======================================================== #
  vue-js:
    image: node:20-alpine
    command: /bin/sh -c "npm install && npm install --save-dev vite && npm run dev"
    ports:
      - ${VUEJS_PORT}:3000
    volumes:
      - "/app/node_modules"
      - "../immo-client-vue-main/:/app"
    working_dir: /app

# ======================================================== #
#                   ░█▀▄░█▀▀░█▀█░█▀▀░▀█▀                   #
#                   ░█▀▄░█▀▀░█▀█░█░░░░█░                   #
#                   ░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░                   #
# ======================================================== #
  react:
    image: node:20-alpine
    command: /bin/sh -c "npm install && npm install --save-dev vite && npm run dev"
    ports:
      - ${REACT_PORT}:3000
    volumes:
      - "/app/node_modules"
      - "../immo-admin-react-main/:/app"
    working_dir: /app